[build]
# The index HTML file to drive the bundling process.
target = "icon_index/index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "../site/"
# The public URL from which assets are to be served.
public_url = "/icondata/"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -m -i input.css -o output.css"]
